name: Parallel running

on:
  push:

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        version: [1, 2, 3, 4, 5, 6, 7, 8, 9, 10]
    name: ${{ matrix.version }
    steps:
    - name: Step 1
      run: |
        echo start
        sleep 10
        echo end

